### ISSUE TITLE
Using ui5-test-runner opens browser windows for tests with puppeteer >= 23.2.0

### ISSUE THREAD

**Issue by heimwege** [ArnaudBuchholz/ui5-test-runner#100]
**Describe the bug**
I increased the version of puppeteer: 22.13.1 -> 23.3.0
When running the tests on my local machine a blank (browser?) window shows up.

![image](https://github.com/user-attachments/assets/13676dd2-6e3c-4058-8288-f51f3939090a)
(this is an actual screenshot 😸 )

Tested with ui5-test-runner 5.3.1 and 5.3.3. Used run command

```
"ui:test:server": "ui5 serve --config ./ui5-test.yaml",
"ui:test:runner": "ui5-test-runner --port 8081 --url http://localhost:8080/test/testsuite.qunit.html --report-generator $/report.js $/junit-xml-report.js --report-dir ./target/QunitReport --coverage true --fail-opa-fast --split-opa --coverage-settings ./.nycrc.json",
"ui:test": "start-server-and-test ui:test:server http://localhost:8080/ ui:test:runner",
```

As soon as I downgrade puppeteer to 23.1.1 everything is back to normal. Issue seems to come from puppeteer >= 23.2.0

**Expected behavior**
No extra window showing up when executing the tests.

**Report**
_Issue not related to any test result_

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
_None_

**Comment by ArnaudBuchholz** [comment]
Tested again with `puppeteer@23.4.1`, problem still present

**Comment by ArnaudBuchholz** [comment]
https://github.com/puppeteer/puppeteer/issues/13145

**Comment by heimwege** [comment]
Fxed with puppeteer v23.6.0
