### ISSUE TITLE
Junit XML output needed

### ISSUE THREAD

**Issue by hudsonvsm** [ArnaudBuchholz/ui5-test-runner#32]
HTML output is nice, but the need for Junit XML for reporting purposes in Jenkins, for example, is needed.

Either XML generation to be done runtime or from a result JSON.

**Comment by hudsonvsm** [comment]
Thank you. 
Can I help if needed?

**Comment by ArnaudBuchholz** [comment]
Hello @hudsonvsm !

I found this [specification](https://llg.cubic.org/docs/junit/) and it seems to be pretty straightforward.
Can you confirm that it is what you are looking for ?

**Comment by ArnaudBuchholz** [comment]
Can you get this file and rename it to XML and confirm that it would work ?
[test.txt](https://github.com/ArnaudBuchholz/ui5-test-runner/files/10830359/test.txt)

**Comment by hudsonvsm** [comment]
Hello @ArnaudBuchholz,

The test.txt looks pretty close to the truth.
Thank you.

**Comment by ArnaudBuchholz** [comment]
Awesome, I am closing the incident and will release v2 soon (will contact you separately). If any problem occurs with the format, feel free to open a new one.
