### ISSUE TITLE
Provide more information about failures in the report console output

### ISSUE THREAD

**Issue by ArnaudBuchholz** [ArnaudBuchholz/ui5-test-runner#53]

**Comment by marianfoo** [comment]
Would be great if browser output would be in the report as well, could be a seperate file?
II could have used that yesterday. :)

**Comment by ArnaudBuchholz** [comment]
The browser console.log is actually saved in a csv file inside the folder associated to the test execution

**Comment by sb-aigh** [comment]
@ArnaudBuchholz We also would like to see more information about failures in the report console output. Would be great if you could improve this.

**Comment by ArnaudBuchholz** [comment]
@marianfoo depending on the browser command, the console output is extracted inside a folder associated to the page execution. I modified the text output to provide the folder name (since it is a hash, it is difficult to guess).

For instance :
```text
[https://ui5.sap.com/test-resources/sap/m/demokit/teamCalendar/webapp/test/integration/opaTests.qunit.html                                                   ]
Page execution folder name : JjE$q8NMfno
Team Calendar ▶ Should see the Planning Calendar initially set
The Planning Calendar rows are not equal to the team members
Opa timeout after 15 seconds
This is what Opa logged:
Found 0 blocking out of 159 tracked timeouts -  sap.ui.test.autowaiter._timeoutWaiter#hasPending
```
