### ISSUE TITLE
"--serve-only" prints wrong url to console

### ISSUE THREAD

**Issue by heimwege** [ArnaudBuchholz/ui5-test-runner#55]
Starting ui5-test-runner with `--port 8081` and `--serve-only` prints the following statement to the console:

`Server running at http://0.0.0.0:8081/`

Clicking on the server url results in an error page (ERR_ADDRESS_INVALID). The correct URL is 

`http://localhost:8081` or `http://127.0.0.1:8081/`

**Comment by ArnaudBuchholz** [comment]
It now gathers the first IPv4 address, fix has been done in `reserve` `1.15.4`

**Comment by ArnaudBuchholz** [comment]
Fixed in `3.3.5`
