### ISSUE TITLE
job step generateCoverageReport not working since 3.3.1

### ISSUE THREAD

**Issue by FrankVisuals** [ArnaudBuchholz/ui5-test-runner#64]
Since version 3.3.1 (3.3.2 did also not work) I received the following error when running my tests:
![image](https://github.com/ArnaudBuchholz/ui5-test-runner/assets/62556998/875fc077-9d86-4f57-8242-5066ec1f559f)

After some investigation I found out that in version 3.3.0 it still worked. I identified these changes as root cause: https://github.com/ArnaudBuchholz/ui5-test-runner/commit/9fdfba049c0a95077f41bfc6526234f9935ab9f5 

The request that tries to read the files 
![image](https://github.com/ArnaudBuchholz/ui5-test-runner/assets/62556998/72a50d96-ccb6-4a90-b606-61bf2d1b50ef)
has the absolute path to the file set as URI path
![Bildschirmfoto 2023-09-27 um 12 31 57](https://github.com/ArnaudBuchholz/ui5-test-runner/assets/62556998/41577968-ab16-415a-b4f3-b31820eafa7b)

Therefore it leads to 404

**Comment by ArnaudBuchholz** [comment]
Thanks for reporting the issue, can you tell me more about your configuration ? how are the files instrumented ?

**Comment by ArnaudBuchholz** [comment]
In the meantime, to unblock your workflow, you may use version `3.3.1` using `npm i -g ui5-test-runner@3.3.1`

**Comment by ArnaudBuchholz** [comment]
reproduced locally, looks like the assumptions are correct.

**Comment by FrankVisuals** [comment]
Sorry for my late response @ArnaudBuchholz 

I've just tested it with version 3.3.4 - it works now! Thanks for the provided fix
