### ISSUE TITLE
Minor documentation improvement

### ISSUE THREAD

**Issue by heimwege** [ArnaudBuchholz/ui5-test-runner#81]
Hey Arnaud,

I just saw that the [TS coverage documentation](https://arnaudbuchholz.github.io/ui5-test-runner/coverage/#typescript-ui5cli-projects-tweaking-ui5-tooling-transpile) mentions 

```
- - transform-ui5
  - overridesToOverride: true
```

The `overridesToOverride` is only needed in ui5 versions < `1.112.x` as mentioned in the [transform-ui5 documentation](https://github.com/ui5-community/babel-plugin-transform-modules-ui5?tab=readme-ov-file#properties-related-to-controller-extensions). So the middleware config can be shortened 😸 

Cheers
Dominik

**Comment by ArnaudBuchholz** [comment]
Added to documentation
